/* Copyright (c) <vendor name> All rights reserved.
   <vendor licensing information, if any> */

// This header contains the peripheral pinout definitions for the
// <name of board or module>

// This file is autogenerated from ../../hardware_definition.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// ADC Controller
#define ADC MT3620_RDB_ADC_CONTROLLER0

// ADC Channel
#define AI0 MT3620_ADC_CHANNEL0

