/* Copyright (c) <vendor name> All rights reserved.
   <vendor licensing information, if any> */

// This header contains the peripheral pinout definitions for the
// <name of board or module>

// This file is autogenerated from ../../pwm_definition.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// PWM Controller connected to LED
#define LED_PWM MT3620_RDB_LED_PWM_CONTROLLER2

