/* Copyright (c) <vendor name> All rights reserved.
   <vendor licensing information, if any> */

// This header contains the peripheral pinout definitions for the
// <name of board or module>

// This file is autogenerated from ../../hardware_definition.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// ISU0 I2C is exposed on header 2, pin 1 (SDA) and pin 7 (SCL)
#define I2C_0 MT3620_ISU0_I2C

