/* Copyright (c) <vendor name> All rights reserved.
   <vendor licensing information, if any> */

// This header contains the peripheral pinout definitions for the
// <name of board or module>

// This file is autogenerated from ../../hardware_definition.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// ISU1 I2C is exposed on header 4, pin 5 (SDA) and pin 11 (SCL)
#define I2C_0 MT3620_RDB_HEADER2_ISU0_I2C

